build: support prepared version processing
Provide support for a translate build request to process a version with
an already prepared releng-tool working tree.

Signed-off-by: James Knight <james.d.knight@live.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -7,6 +7,7 @@ set -e
 help=0
 locale_dir=
 target=
+target_dir=
 while [ "$#" -gt 0 ]; do
     case $1 in
         --help)
@@ -21,6 +22,10 @@ while [ "$#" -gt 0 ]; do
         target="$2"
         shift
         ;;
+        --version-dir)
+        target_dir="$2"
+        shift
+        ;;
     esac
     shift
 done
@@ -32,8 +37,16 @@ fetch <options>
  -h, --help                show this help
  -L, --locale <dir>        the directory to fetch locale data from
  --version <version>       build only a specific version
+ --version-dir <dir>       prepared directory to use for the version build
 HELP_EOM
     exit 0
+fi
+
+if [ -n "$target_dir" ]; then
+    if [ -z "$target" ]; then
+        echo "error) provided a version directory without a version"
+        exit 1
+    fi
 fi
 
 ################################################################################
@@ -105,15 +118,20 @@ for version in "${!versions[@]}"; do
     lang_list=${lang_list:1}
 
     for lang in "${languages[@]}"; do
-        target_dir=$out_dir/$lang/$version
+        lang_target_dir=$out_dir/$lang/$version
         echo -e "\e[7mbuilding $version ($lang)...\e[0m"
 
-        # checkout specific documentation version
-        mkdir -p $base/$workdir/$doc_container
-        git \
-            --git-dir="$base/$cache/$doc_container" \
-            --work-tree="$base/$workdir/$doc_container" \
-            checkout $reference --force
+        if [ -n "$target_dir" ]; then
+            export RELENG_TARGET_DIR=$target_dir
+        else
+            # checkout specific documentation version
+            mkdir -p $base/$workdir/$doc_container
+            git \
+                --git-dir="$base/$cache/$doc_container" \
+                --work-tree="$base/$workdir/$doc_container" \
+                checkout $reference --force
+            export RELENG_TARGET_DIR=$base/$workdir/$doc_container
+        fi
 
         # build documentation
         export RELENG_LANGUAGE=$lang
@@ -126,6 +144,6 @@ for version in "${!versions[@]}"; do
             -Dlanguage=$lang \
             -b $builder \
             $base \
-            $target_dir
+            $lang_target_dir
     done
 done
